### ISSUE TITLE
LoggedIn to WHAT?

### ISSUE THREAD

**Issue by bendspoons** [EternallLight/cordova-plugin-openwith-ios#20]
Just a simple question: logged to WHAT? I have absolutely NO Idea, what this means.

**Comment by EternallLight** [comment]
This is intended for usage in apps that require signing in before sharing. Unless you are sign in, you cannot share the data to your contacts in the app, for instance. It is disabled by default, so if you don't need it, you don't have to worry about it.

**Comment by bendspoons** [comment]
thanks for the reply, but it says always I'm not logged in. Always, i does not matter what i do.

Normally, when adding 

`  // Set logged in status
  cordova.openwith.setLoggedIn(true);`

the login shouldn't be asked. But it does. Always. Wouldn't it be nice, if such a special feature would ONLY be available if i explicitly enable it?

**Comment by bendspoons** [comment]
Hey, im sorry for being that explicit in my comment. Had a rough day where nothing worked. Made a fork and make my needed changes there. Thanks for the work!

**Comment by EternallLight** [comment]
@bendspoons thank you for the report. I removed the isLoggedIn functionality completely from the version 2 of the plugin as it seems to be a very specific case. Feel free to use this branch https://github.com/EternallLight/cordova-plugin-openwith-ios/tree/release/v2.0.0 before it is merged into master.
